2024-05-30 17:02:05,259 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-30 17:02:05,259 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Configure stats pid to 12674
2024-05-30 17:02:05,259 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Loading settings from /Users/zhemingan/.config/wandb/settings
2024-05-30 17:02:05,259 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Loading settings from /Users/zhemingan/anaconda3/lib/python3.11/site-packages/signaturesnet/wandb/settings
2024-05-30 17:02:05,260 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-30 17:02:05,260 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-30 17:02:05,260 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_generator.py', 'program_abspath': '/Users/zhemingan/anaconda3/lib/python3.11/site-packages/signaturesnet/train_generator.py', 'program': '/Users/zhemingan/anaconda3/lib/python3.11/site-packages/signaturesnet/train_generator.py'}
2024-05-30 17:02:05,260 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-30 17:02:05,260 INFO    MainThread:12674 [wandb_init.py:_log_setup():520] Logging user logs to /Users/zhemingan/anaconda3/lib/python3.11/site-packages/signaturesnet/wandb/run-20240530_170205-gmpw12wz/logs/debug.log
2024-05-30 17:02:05,260 INFO    MainThread:12674 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/zhemingan/anaconda3/lib/python3.11/site-packages/signaturesnet/wandb/run-20240530_170205-gmpw12wz/logs/debug-internal.log
2024-05-30 17:02:05,260 INFO    MainThread:12674 [wandb_init.py:init():560] calling init triggers
2024-05-30 17:02:05,260 INFO    MainThread:12674 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'data_id': 'real_data', 'model_id': 'cancer_type_oversampler_1', 'models_dir': '../trained_models/fix_generator_oversample/', 'cosmic_version': 'v3', 'type': 'real', 'iterations': 500, 'num_classes': 60, 'lagrange_param': 0.001, 'batch_size': 100, 'lr_encoder': 0.005, 'lr_decoder': 0.0005, 'enable_logging': True, 'wandb_project_id': 'fix_generator_oversample', 'num_hidden_layers': 5, 'latent_dim': 100, 'device': 'cuda'}
2024-05-30 17:02:05,260 INFO    MainThread:12674 [wandb_init.py:init():610] starting backend
2024-05-30 17:02:05,260 INFO    MainThread:12674 [wandb_init.py:init():614] setting up manager
2024-05-30 17:02:05,263 INFO    MainThread:12674 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-30 17:02:05,265 INFO    MainThread:12674 [wandb_init.py:init():622] backend started and connected
2024-05-30 17:02:05,278 INFO    MainThread:12674 [wandb_init.py:init():711] updated telemetry
2024-05-30 17:02:05,279 INFO    MainThread:12674 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-30 17:02:05,452 ERROR   MainThread:12674 [wandb_init.py:init():770] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-30 17:02:05,452 ERROR   MainThread:12674 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/Users/zhemingan/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/zhemingan/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-05-30 17:02:44,495 INFO    MainThread:12674 [wandb_settings.py:_apply_login():1895] Applying login settings: {}
2024-05-30 17:02:44,497 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Current SDK version is 0.17.0
2024-05-30 17:02:44,497 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Configure stats pid to 12674
2024-05-30 17:02:44,497 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Loading settings from /Users/zhemingan/.config/wandb/settings
2024-05-30 17:02:44,497 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Loading settings from /Users/zhemingan/anaconda3/lib/python3.11/site-packages/signaturesnet/wandb/settings
2024-05-30 17:02:44,497 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-05-30 17:02:44,497 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-05-30 17:02:44,497 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'train_generator.py', 'program_abspath': '/Users/zhemingan/anaconda3/lib/python3.11/site-packages/signaturesnet/train_generator.py', 'program': '/Users/zhemingan/anaconda3/lib/python3.11/site-packages/signaturesnet/train_generator.py'}
2024-05-30 17:02:44,497 INFO    MainThread:12674 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-05-30 17:02:44,497 INFO    MainThread:12674 [wandb_init.py:_log_setup():520] Logging user logs to /Users/zhemingan/anaconda3/lib/python3.11/site-packages/signaturesnet/wandb/run-20240530_170244-1hsrpnax/logs/debug.log
2024-05-30 17:02:44,497 INFO    MainThread:12674 [wandb_init.py:_log_setup():521] Logging internal logs to /Users/zhemingan/anaconda3/lib/python3.11/site-packages/signaturesnet/wandb/run-20240530_170244-1hsrpnax/logs/debug-internal.log
2024-05-30 17:02:44,497 INFO    MainThread:12674 [wandb_init.py:init():560] calling init triggers
2024-05-30 17:02:44,498 INFO    MainThread:12674 [wandb_init.py:init():567] wandb.init called with sweep_config: {}
config: {'data_id': 'datasets/detector', 'model_name': 'nummutnet', 'iterations': 2000, 'batch_size': 200, 'lr': 0.0001, 'enable_logging': True, 'wandb_project_id': 'nummutnet', 'num_hidden_layers': 1, 'num_neurons': 5000, 'device': 'cpu'}
2024-05-30 17:02:44,498 INFO    MainThread:12674 [wandb_init.py:init():610] starting backend
2024-05-30 17:02:44,498 INFO    MainThread:12674 [wandb_init.py:init():614] setting up manager
2024-05-30 17:02:44,499 INFO    MainThread:12674 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-05-30 17:02:44,499 INFO    MainThread:12674 [wandb_init.py:init():622] backend started and connected
2024-05-30 17:02:44,502 INFO    MainThread:12674 [wandb_init.py:init():711] updated telemetry
2024-05-30 17:02:44,502 INFO    MainThread:12674 [wandb_init.py:init():744] communicating run to backend with 90.0 second timeout
2024-05-30 17:02:44,657 WARNING MsgRouterThr:12674 [router.py:message_loop():77] message_loop has been closed
2024-05-30 17:02:44,657 ERROR   MainThread:12674 [wandb_init.py:init():770] encountered error: [Errno 32] Broken pipe
2024-05-30 17:02:44,657 ERROR   MainThread:12674 [wandb_init.py:init():1174] error in wandb.init()
Traceback (most recent call last):
  File "/Users/zhemingan/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1164, in init
    return wi.init()
           ^^^^^^^^^
  File "/Users/zhemingan/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 776, in init
    raise error
wandb.errors.CommError: [Errno 32] Broken pipe
